dom-event-delegation -- Sarah You
sarah-you/c0323-code-solutions pull request #47
Opened 2023-04-06 21:12 UTC by sarah-you

https://user-images.githubusercontent.com/103456134/230495016-81f0b04c-7462-4b37-a7d7-f6b30fe92c4a.mov

2023-04-06 21:13 UTC, sarah-you commented
<img width="1431" alt="dom-event-delegation" src="https://user-images.githubusercontent.com/103456134/230495072-00f5f82b-cea6-4c04-baff-bd8ecc8a1976.png">

2023-04-07 15:25 UTC, shawnkost requested changes
One change requested on your quiz answer!

2023-04-07 15:25 UTC, shawnkost commented on dom-event-delegation/dom-event-delegation-quiz-notes.md
> +the element you are adding the event listener to;
Not quite! `event.target` is the element that was interacted with to trigger the event. `event.currentTarget` would be the element that has the event listener attached to it.

2023-04-10 15:51 UTC, shawnkost approved these changes
👍🏻

2023-04-10 16:34 UTC, merged